apiVersion: sailoperator.io/v1
kind: Istio
metadata:
  name: {{ .Values.servicemesh.istio.name | quote }}
spec:
  version: {{ .Values.servicemesh.version | quote }}
  namespace: {{ .Values.servicemesh.istio.namespace | default .Release.Namespace | quote }}
  {{- if .Values.servicemesh.profile }}
  profile: {{ .Values.servicemesh.profile }}
  {{- end }}
  {{- if .Values.servicemesh.istio.updateStrategy }}
  updateStrategy:
{{ toYaml .Values.servicemesh.istio.updateStrategy | indent 4 }}
  {{- end }}
  {{- if .Values.servicemesh.istio.values }}
  values:
{{ toYaml .Values.servicemesh.istio.values | indent 4 }}
  {{- end }}
