{{- if .Values.servicemesh.console.enabled }}
apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: {{ .Values.servicemesh.kiali.name | quote }}
  namespace: {{ .Values.servicemesh.istio.namespace | default .Release.Namespace | quote }}
spec:
{{ toYaml .Values.servicemesh.kiali.spec | indent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kiali-monitoring-rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-monitoring-view
subjects:
- kind: ServiceAccount
  name: kiali-service-account
  namespace: istio-system
{{- end }}
