{{- if .Values.servicemesh.ztunnel.enabled }}
apiVersion: sailoperator.io/v1alpha1
kind: ZTunnel
metadata:
  name: {{ .Values.servicemesh.ztunnel.name | quote }}
spec:
  version: {{ .Values.servicemesh.version | quote }}
  namespace: {{ .Values.servicemesh.ztunnel.namespace | default .Release.Namespace | quote }}
  {{- if .Values.servicemesh.profile }}
  profile: {{ .Values.servicemesh.profile | quote }}
  {{- end }}
  {{- if .Values.servicemesh.ztunnel.values }}
  values:
{{ toYaml .Values.servicemesh.ztunnel.values | indent 4 }}
  {{- end }}
{{- end }}
